superherosproject/superheroes/urls.py
from django.urls import path
from . import views


app_name = 'superheroes'
urlpatterns = [
    path('', views.index, name='index'),
    path('detail/<int:superhero_id>/', views.detail, name='detail'),
    path('new/', views.create, name='create'),
    path('<int:superhero_id>/delete/', views.delete, name='delete')
]

superherosproject/superherosproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('superheroes/', include('superheroes.urls')),
    path('', RedirectView.as_view(url='/superheroes/'))
]

superherosproject/superheroes/models.py
from django.db import models

# Create your models here.

class Superhero(models.Model):
    name = models.CharField(max_length=50)
    alter_ego = models.CharField(max_length=50)
    primary_ability = models.CharField(max_length=50)
    secondary_ability = models.CharField(max_length=50)
    catchphrase = models.CharField(max_length=50)


    def __str__(self):
        return self.name

superherosproject/superheroes/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Superhero
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse

# Create your views here.

def index(request):
    all_superheroes = Superhero.objects.all()
    context = {
        'all_superheroes': all_superheroes
    }
    return render(request, 'superheroes/index.html', context)

def detail(request, superhero_id):
    superhero = Superhero.objects.get(id=superhero_id)
    context = {
        'superhero': superhero
    }
    return render(request, 'superheroes/detail.html', context)

def create(request):
    if request.method == "POST":
        name = request.POST.get('name')
        alter_ego = request.POST.get('alter_ego')
        primary_ability = request.POST.get('primary_ability')
        secondary_ability = request.POST.get('secondary_ability')
        catchphrase = request.POST.get('catchphrase')
        new_superhero = Superhero(name=name, alter_ego=alter_ego, primary_ability=primary_ability, secondary_ability=secondary_ability, catchphrase=catchphrase)
        new_superhero.save()
        return HttpResponseRedirect(reverse('superheroes:index'))
    else:
        return render(request, 'superheroes/create.html')

def delete(request, superhero_id):

    context ={}
 
    superhero = Superhero.objects.get(id = superhero_id)
 
 
    if request.method =="POST":
        # delete object
        superhero.delete()
        # after deleting redirect to
        # home page
        return HttpResponseRedirect(reverse('superheroes:index'))
 
    return render(request, "superheroes/delete.html", context)

superherosproject/superheroes/templates/superheroes/create.html
<form action="{% url 'superheroes:create' %}" method="post">
    {% csrf_token %}
    Name:<input type="text" name="name" id="name"><br>
    Alter Ego:<input type="text" name="alter_ego" id="alter_ego"><br>
    Primary Ability: <input type="text" name="primary_ability" id="primary_ability"><br>
    Secondary Ability: <input type="text" name="secondary_ability" id="secondary_ability"><br>
    Catchphrase: <input type="text" name="catchphrase" id="catchprhase"><br>
    <input type="submit" value="Add new!">
</form>

superherosproject/superheroes/templates/superheroes/delete.html
<div class="main">
    <!-- Create a Form -->
    <form method="POST">
        <!-- Security token by Django -->
        {% csrf_token %}
        <p>Are you sure you want to delete this item ?</p>
        <input type="submit" value="Yes" />
        <a href="{% url 'superheroes:index' %}">Cancel </a>
    </form>
</div>

superherosproject/superheroes/templates/superheroes/detail.html
{% block title %} <h1>Superhero Details</h1> {% endblock %} 
 

{% block content %} 

<div>
    <h3>Name: </h3>
    <p>{{superhero.name}}</p>
    <h3>Alter Ego: </h3>
    <p>{{superhero.alter_ego}}</p>
    <h3>Primary Ability: </h3>
    <p>{{superhero.primary_ability}}</p>
    <h3>Secondary Ability: </h3>
    <p>{{superhero.secondary_ability}}</p>
    <h3>Catchphrase: </h3>
    <p>{{superhero.catchphrase}}</p>
</div>




{% endblock %}

superherosproject/superheroes/templates/superheroes/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Superhero Index</title>
</head>
<body>
    <h1>List of Superheroes</h1>
    <img src = "image.jpg" alt="Vanya">
    
    <table style="border-collapse: collapse; border-color: blue;">
        <thead>
            <tr>
                <th>Name</th>
                <th>Details</th>
                <th>Delete</th>
                
            </tr>
        </thead>
        <tbody>
            {%for superhero in all_superheroes %}
            <tr>
                <td>{{superhero.name}}</td>
                <td><a href="{% url 'superheroes:detail' superhero.id %}">Details</a></td>
                <td><a style="background-color: red" href="{% url  'superheroes:delete' superhero.id %}">Delete</a></td>
            </tr>
            {% endfor %}

        </tbody>
    </table>
    <a href="{% url 'superheroes:create' %}">Create</a>
</body>
</html>